### ISSUE TITLE
entryproperties option blocks

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#232]
I tweaked the entryproperties plugin to float the smaller option blocks. See example

![ep-blocks](https://cloud.githubusercontent.com/assets/1105372/5087175/85b64ab8-6f25-11e4-98f4-d5d7f89b584c.png)

For the css I did this by adding plugin streamed css. Do you want me to push it like this or give you the chance to add this to admin/style.css ? The first, without the media, is to have the full size option blocks the same width as all other blocks have.

``` css
#edit_entry_freetags div, 
.entryproperties_customfields {
    margin-right: 2%;
}

@media only screen and (min-width: 768px) {
    #ep_sticky,
    #ep_gather,
    #ep_frontpage,
    #ep_hiderss,
    #ep_access_list,
    #ep_access_pw,
    #ep_access_groups,
    #ep_access_users,
    #ep_access_author,
    #ep_markup {
        float: left;
        margin-right: 2%;
        width: 48%;
    }
    #ep_access_list {
        margin-top: 0.75em;
    }
    #ep_access_pw input {
        width: 70%;
    }
}

```
