### ISSUE TITLE
set a strict minimum box size to the layer

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#265]
Set smallest smartphone width as a default minmum box size to the layer, see example
![set-min-size](https://cloud.githubusercontent.com/assets/1105372/5788491/4a24ae3e-9e39-11e4-926c-9b5bd84315cf.png)
in example to play around...
```css
.mfp-image-holder .mfp-content {
    max-width: 100%;
    min-width: 16em;
    min-height: 16em;
    padding: 1%;
}
```
![set-min-size-patched-320](https://cloud.githubusercontent.com/assets/1105372/5788518/14c1d0e4-9e3b-11e4-80b2-ac8efd439a33.png)
