### ISSUE TITLE
square media library and theme preview boxes

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#73]
Now, a long height image sets the height for all boxes, which is bad if the one is the only one.

This is what I meant to have:
 ```css
.js .media_file_preview,
.js .template_preview {
    max-height: 330px;
}
.js .equal_heights {
    overflow: auto;
}
```
After, all boxes are squared in desktop view, smaller images stay like they are, very heigh images are flowed and smaller screens don't care or set a responsive max-height for ```@media only screens```.

What do you think?

**Comment by ophian** [comment]
Just updated an old blog to 2.0 release and have this:
![defaultminsize](https://cloud.githubusercontent.com/assets/1105372/5873470/21a65580-a2f7-11e4-98c5-bd8500a53bb6.png)
which tells me that we **need** a default min size for the info box and layer.

**Comment by ophian** [comment]
I think I already told you, that I personally use css only, to overwrite the js inline inserted max-width: 110px; with a min-height: 17.5em; in here:
```css
.js .media_pane .media_file_meta,
.js .template_info {
    background: #222;
    background: rgba(0,0,0,.6);
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    color: #fcfcfc;
    height: 100%;
    min-height: 17.5em;
    overflow: auto;
    padding: .5em 1em;
    position: absolute;
    top: 0;
    left: 0;
    text-shadow: 1px 1px 1px rgba(0,0,0,.8);
    width: 100%;
}
```
and adding these two
```css
    .media_file_wrap {
        min-height: 19em !important; /* overwrite inline equal heights */
        overflow: auto;
        max-height: 19em; /* strict max size*/
    }
    .has_author {
        min-height: 17.5em !important; /* overwrite inline equal heights */
        overflow: auto;
        max-height: 17.5em; /* strict max size*/
    }
```
right before the 
```css
    .taxonomy ul {
        clear: none;
        float: right;
        width: 84%;
    }
```
somewhere between ln 2900-3000.

And this works perfectly well for me, well, I couldn' check this on touch devices though...

And the important force thing of course just being currently needed to overwrite the js function, which could be disabled.
